import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";
import MemphisBackground from "@/components/MemphisBackground";

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Tournament Scheduler",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fredoka.variable} antialiased`}
      >
        <MemphisBackground />
        {children}
      </body>
    </html>
  );
}
